### ISSUE TITLE
Unprotected access to strings in ContextSensitiveEventLogger

### ISSUE THREAD

**Issue by ryansgot** [ryansgot/logging#32]
It is possible for the Main thread's cache to have these values set:

```kotlin
    protected lateinit var appUptimeAttrName: String
    protected lateinit var timestampAttrName: String
```

But the thread handling logging to not see the update. 

Here's a stacktrace:
```
02-22 10:12:47.280 25698 25900 E AndroidRuntime: FATAL EXCEPTION: FSEventLog-pool-5-thread-1
02-22 10:12:47.280 25698 25900 E AndroidRuntime: Process: my.app.package, PID: 25698
02-22 10:12:47.280 25698 25900 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property appUptimeAttrName has not been initialized
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.android.ContextSpecificEventLogger.getAppUptimeAttrName(ContextSpecificEventLogger.kt:25)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.android.ContextSpecificEventLogger.addDefaultAttrsTo(ContextSpecificEventLogger.kt:77)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.android.newrelic.NewRelicEventLogger.addEvent(NewRelicEventLogger.kt:60)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.FSEventLog$addEvent$1$1.invoke(FSEventLog.kt:180)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.FSEventLog$addEvent$1$1.invoke(FSEventLog.kt:180)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.FSLoggersKt.onSomeOrAll(FSLoggers.kt:161)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.FSEventLog.addEvent$lambda-8(FSEventLog.kt:180)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.FSEventLog.$r8$lambda$t1mCWqO9YUs4-0gnQnVIkqeg6o4(Unknown Source:0)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at com.fsryan.tools.logging.FSEventLog$$ExternalSyntheticLambda4.run(Unknown Source:6)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-22 10:12:47.280 25698 25900 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:920)
```

**Comment by ryansgot** [comment]
Fixed in PR #33
